from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

from jarvis.utils.time_utils import utc_now_iso


@dataclass(frozen=True)
class CRSISSignal:
    key: str
    value: float
    threshold: float
    comparator: str
    severity: str = "warn"
    message: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class CRSISFinding:
    signal_key: str
    severity: str
    message: str
    value: float
    threshold: float
    comparator: str


@dataclass(frozen=True)
class CRSISSnapshot:
    timestamp: str
    source: str
    status: str
    signals: tuple[CRSISSignal, ...]
    findings: tuple[CRSISFinding, ...]
    metadata: dict[str, Any] = field(default_factory=dict)


# =============================================================================
# Phase 1: Observation Layer - Satisfaction Signals
# =============================================================================


@dataclass(frozen=True)
class SatisfactionSignal:
    """User satisfaction signal for CRSIS observation layer."""

    turn_id: str
    signal_type: str  # "correction", "re_ask", "acceptance", "abandonment"
    confidence: float
    evidence: dict[str, Any]
    timestamp: str = field(default_factory=utc_now_iso)


# =============================================================================
# Phase 2: Decision Log Analysis - Pattern Findings
# =============================================================================


@dataclass(frozen=True)
class PatternFinding:
    """Detected pattern from decision log analysis."""

    pattern_type: str  # "misrouting", "empty_tool", "correction_cluster"
    affected_component: str  # e.g., "prompt_dispatcher:EXACT_INTENTS"
    evidence_count: int
    confidence: float
    examples: list[str]
    time_range: tuple[str, str]


# =============================================================================
# Phases 3-6: CRSIS Proposals and Application
# =============================================================================


@dataclass
class CRSISProposal:
    """Improvement proposal generated by CRSIS."""

    proposal_id: str
    proposal_type: str  # "new_phrase", "threshold_change", "synonym_add", "tool_registration", "retention_change"
    target_file: str
    target_structure: str  # e.g., "EXACT_INTENTS", "HEAVY_PHRASES"
    proposed_change: dict[str, Any]
    evidence: list[PatternFinding]
    expected_impact: str
    rollback_path: str
    created_at: str = field(default_factory=utc_now_iso)
    status: str = (
        "pending"  # "pending", "approved", "rejected", "applied", "rolled_back"
    )

    def approve(self) -> None:
        """Mark proposal as approved."""
        self.status = "approved"

    def reject(self) -> None:
        """Mark proposal as rejected."""
        self.status = "rejected"

    def mark_applied(self) -> None:
        """Mark proposal as applied."""
        self.status = "applied"

    def mark_rolled_back(self) -> None:
        """Mark proposal as rolled back."""
        self.status = "rolled_back"


@dataclass(frozen=True)
class ChangeResult:
    """Result of a code change operation."""

    success: bool
    backup_path: str | None = None
    error: str | None = None
    validation_passed: bool = False
    validation_output: str = ""


@dataclass(frozen=True)
class CRSISLoopResult:
    """Result of a CRSIS loop execution."""

    patterns_detected: int
    proposals_generated: int
    auto_applied: int
    applied_successfully: int = 0
    rolled_back: int = 0
