from __future__ import annotations

from jarvis.brain_core.tool_policy import ToolMetadata, LanePolicy, LatencyClass

TOOL_MANIFEST = {
    "local_now": ToolMetadata(
        tool_name="local_now",
        purpose="Get current local time",
        example_queries=["what time is it", "current time"],
        lane_policy=LanePolicy.REALTIME,
        latency_class=LatencyClass.FAST,
        expected_max_ms=10.0,
        domain_tags=["time", "utility"],
    ),
    "utc_now_iso": ToolMetadata(
        tool_name="utc_now_iso",
        purpose="Get current UTC time in ISO format",
        example_queries=["utc time", "iso timestamp"],
        lane_policy=LanePolicy.REALTIME,
        latency_class=LatencyClass.FAST,
        expected_max_ms=10.0,
        domain_tags=["time", "utility"],
    ),
    "calculator": ToolMetadata(
        tool_name="calculator",
        purpose="Evaluate mathematical expressions",
        example_queries=["calculate 2+2", "what is 15% of 200"],
        lane_policy=LanePolicy.REALTIME,
        latency_class=LatencyClass.FAST,
        expected_max_ms=50.0,
        domain_tags=["math", "utility"],
    ),
    "file_write": ToolMetadata(
        tool_name="file_write",
        purpose="Write content to a file",
        example_queries=["save this to file.txt", "write hello to test.txt"],
        lane_policy=LanePolicy.REALTIME,
        latency_class=LatencyClass.MODERATE,
        expected_max_ms=100.0,
        requires_confirmation=True,
        confirmation_action="file_write",
        domain_tags=["file", "io"],
    ),
    "code_runner": ToolMetadata(
        tool_name="code_runner",
        purpose="Execute Python code",
        example_queries=["run this python code", "execute print('hello')"],
        lane_policy=LanePolicy.EITHER,
        latency_class=LatencyClass.SLOW,
        expected_max_ms=5000.0,
        requires_confirmation=True,
        confirmation_action="code_runner",
        domain_tags=["code", "execution"],
    ),
    "app_launch": ToolMetadata(
        tool_name="app_launch",
        purpose="Launch an application",
        example_queries=["open firefox", "launch spotify"],
        lane_policy=LanePolicy.REALTIME,
        latency_class=LatencyClass.MODERATE,
        expected_max_ms=500.0,
        requires_confirmation=True,
        confirmation_action="app_ops",
        capability="app_ops",
        domain_tags=["system", "app"],
    ),
    "app_focus": ToolMetadata(
        tool_name="app_focus",
        purpose="Focus/switch to an application window",
        example_queries=["switch to chrome", "focus terminal"],
        lane_policy=LanePolicy.REALTIME,
        latency_class=LatencyClass.FAST,
        expected_max_ms=100.0,
        requires_confirmation=True,
        confirmation_action="app_ops",
        capability="app_ops",
        domain_tags=["system", "app"],
    ),
    "web_search": ToolMetadata(
        tool_name="web_search",
        purpose="Search the web for information",
        example_queries=["search for python tutorials", "look up weather"],
        lane_policy=LanePolicy.EITHER,
        latency_class=LatencyClass.SLOW,
        expected_max_ms=3000.0,
        domain_tags=["web", "search"],
    ),
    "web_fetch": ToolMetadata(
        tool_name="web_fetch",
        purpose="Fetch and extract content from a webpage",
        example_queries=["check heraldd.vercel.app", "fetch this page"],
        lane_policy=LanePolicy.EITHER,
        latency_class=LatencyClass.SLOW,
        expected_max_ms=5000.0,
        domain_tags=["web", "fetch"],
    ),
    "memory_tool": ToolMetadata(
        tool_name="memory_tool",
        purpose="Inspect and manage memory entries",
        example_queries=["what do you remember", "forget my address"],
        lane_policy=LanePolicy.REALTIME,
        latency_class=LatencyClass.FAST,
        expected_max_ms=50.0,
        domain_tags=["memory", "utility"],
    ),
    "intent_miss_get": ToolMetadata(
        tool_name="intent_miss_get",
        purpose="Get recent intent misses for debugging",
        example_queries=["show intent misses", "what did you miss"],
        lane_policy=LanePolicy.REALTIME,
        latency_class=LatencyClass.FAST,
        expected_max_ms=50.0,
        domain_tags=["debug", "observability"],
    ),
    "intent_miss_stats": ToolMetadata(
        tool_name="intent_miss_stats",
        purpose="Get intent miss statistics",
        example_queries=["intent miss stats", "how many misses"],
        lane_policy=LanePolicy.REALTIME,
        latency_class=LatencyClass.FAST,
        expected_max_ms=50.0,
        domain_tags=["debug", "observability"],
    ),
    "intent_miss_patterns": ToolMetadata(
        tool_name="intent_miss_patterns",
        purpose="Get aggregated intent miss patterns",
        example_queries=["intent patterns", "common misses"],
        lane_policy=LanePolicy.REALTIME,
        latency_class=LatencyClass.FAST,
        expected_max_ms=50.0,
        domain_tags=["debug", "observability"],
    ),
    "job_status": ToolMetadata(
        tool_name="job_status",
        purpose="Check status of background tasks",
        example_queries=["what are you doing", "bg1 status"],
        lane_policy=LanePolicy.REALTIME,
        latency_class=LatencyClass.FAST,
        expected_max_ms=10.0,
        domain_tags=["system", "bg1"],
    ),
    "screen_capture": ToolMetadata(
        tool_name="screen_capture",
        purpose="Capture the screen",
        example_queries=["take a screenshot", "capture the screen"],
        lane_policy=LanePolicy.EITHER,
        latency_class=LatencyClass.MODERATE,
        expected_max_ms=500.0,
        domain_tags=["vision", "system"],
    ),
    "ocr_read": ToolMetadata(
        tool_name="ocr_read",
        purpose="Read text from images via OCR",
        example_queries=["read the text in this image"],
        lane_policy=LanePolicy.EITHER,
        latency_class=LatencyClass.SLOW,
        expected_max_ms=3000.0,
        domain_tags=["vision", "ocr"],
    ),
    "set_volume": ToolMetadata(
        tool_name="set_volume",
        purpose="Set system audio volume (0-100)",
        example_queries=["set volume to 50", "mute audio"],
        lane_policy=LanePolicy.REALTIME,
        latency_class=LatencyClass.FAST,
        expected_max_ms=100.0,
        domain_tags=["system", "audio"],
    ),
    "get_volume": ToolMetadata(
        tool_name="get_volume",
        purpose="Get current system audio volume",
        example_queries=["what is the volume"],
        lane_policy=LanePolicy.REALTIME,
        latency_class=LatencyClass.FAST,
        expected_max_ms=100.0,
        domain_tags=["system", "audio"],
    ),
    "get_thermal_status": ToolMetadata(
        tool_name="get_thermal_status",
        purpose="Get system thermal health (CPU/GPU temperature)",
        example_queries=["is my computer hot", "check temperature"],
        lane_policy=LanePolicy.REALTIME,
        latency_class=LatencyClass.FAST,
        expected_max_ms=100.0,
        domain_tags=["system", "health"],
    ),
    "web_scrape_chromium": ToolMetadata(
        tool_name="web_scrape_chromium",
        purpose="Scrape a webpage using a real browser (Chromium/Playwright)",
        example_queries=["scrape this dynamic site", "render this page"],
        lane_policy=LanePolicy.EITHER,
        latency_class=LatencyClass.SLOW,
        expected_max_ms=10000.0,
        domain_tags=["web", "scrape"],
    ),
    "web_crawl_chromium": ToolMetadata(
        tool_name="web_crawl_chromium",
        purpose="Crawl multiple pages using a real browser",
        example_queries=["crawl this site", "deep scan this website"],
        lane_policy=LanePolicy.BG1,
        latency_class=LatencyClass.SLOW,
        expected_max_ms=30000.0,
        domain_tags=["web", "crawl"],
    ),
}
